### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by hzw20200301** [likenneth/persona_drift#1]
Thank you for your excellent work. May I ask if the evaluation code for the dataset located at https://huggingface.co/datasets/Naomibas/llm-system-prompts-benchmark is no longer supported?

**Comment by likenneth** [comment]
I believe it's the same as https://github.com/likenneth/persona_drift/blob/master/hundred_system_prompts.py

This one will continue to be supported.

**Comment by hzw20200301** [comment]
Thank you for responding. I noticed that the github link and files on Hugging Face are different, so I jumped to the conclusion that it was no longer supported.
