### ISSUE TITLE
Inquiry Regarding Code for SPR, CFG, and SS Methods

### ISSUE THREAD

**Issue by yftah89** [likenneth/persona_drift#2]
Dear authors, 
Thank you for sharing your code with the community :) 

I’ve been reviewing your repository and am particularly interested in the implementations of the methods presented in your paper (SPR, CFG, and SS). However, I’m having a bit of difficulty locating the relevant code.

Would you kindly point me in the right direction?

Thank you in advance for your help!

**Comment by likenneth** [comment]
Hello, 

I didn't put the code for the three mitigation methods in here. They work in very different ways and it's hard to unify them in implementation. 

Which is of particular interest to you?

**Comment by likenneth** [comment]
Please let me know if this ticket should be reopened.
