### ISSUE TITLE
Reproduce figure4 in the paper

### ISSUE THREAD

**Issue by kenoharada** [likenneth/persona_drift#3]
Thank you for sharing your very interesting work!

I would like to investigate the relationship between allocated attention and instruction following performance.

Can you share the code for reproduce figure4 in the paper?

Or

Can you share the details about how to calculate allocated attention to the system prompt(Y-axis of Figure4)?

Thanks

**Comment by likenneth** [comment]
Hello! 

In each attention head of Transformer, there is a map A where the element (i, j) calculates the i-th tokens attention distribution over all the T tokens (including itself). 

The x-axis here is i, y axis is \sum_{k=1}^{length of the system prompt} A_{i,k}.

Please let me know if you have any more questions!

**Comment by kenoharada** [comment]
Thank you for the quick response!

As final clarification, 
Y-axis is sum of all heads and all layers? or Did you choose some attention head of specific layer or sum all attention heads over specific layer?

**Comment by likenneth** [comment]
The plot I showed is only for one attention head, but it's easy to see that all of them look similar, except for heads from the first several Transformer layers.

**Comment by kenoharada** [comment]
Thank you very much!!!
